### ISSUE TITLE
Not Trying to be rude or anything .so please dont take it that way 

### ISSUE THREAD

**Issue by ghost** [s4msecurity/Dork_List_And_Smart_Search#1]
But you should Run it through Anti Dupe Remover .

original lines - 10,509 
removed- 5,238 
remaining- 5,271

**Comment by s4msecurity** [comment]
Hi Hail2Hydra..
Nope, I like your idea share with me. But I don't understand. What you did mean with "Anti Dupe Remover"?

**Comment by ghost** [comment]
Sorry!

I meant Remove duplicate lines that are inside of file . there is over 5,000 Repeated lines.

Here is a site that i use alot !

https://dedupelist.com

**Comment by s4msecurity** [comment]
Thank you for your valuable thoughts, I edited it again.
Could you please check and close the issue?
